### PR TITLE
Migrate to upstream 2.26.0.

### PR DESCRIPTION
**Pull request by d3zd3z**

### CODE REVIEW

**Comment by ioannisg** [comment]
CC @microbuilder

**Review by MaureenHelm — APPROVED** [review]

**Comment by microbuilder** [comment]
@d3zd3z Do you mind adding me as a reviewer to this, or is there a specific process for the crypto libs?

**Comment by microbuilder** [comment]
What is the ideal mechanism to expose `MBEDTLS_USE_PSA_CRYPTO` to consumers of mbedtls? We need to set this in mbedtls to use the PSA APIs as a backend for TF-M, etc.

Should we have a KConfig option for that in [Kconfig.mbedtls](https://github.com/zephyrproject-rtos/zephyr/blob/master/modules/Kconfig.mbedtls), or just rely on users defining a custom mbed config file that sets this option?

**Comment by ioannisg** [comment]
> @d3zd3z Do you mind adding me as a reviewer to this, or is there a specific process for the crypto libs?

you need to be collaborator i the repository, I guess @galak can fix that.

**Comment by ioannisg** [comment]
@d3zd3z @ceolin the problem I see, doing the update this way, is that we cannot directly use the checked-out version in this module, as the mbedcrypto path to build TF-M; assume the problem is the missing files. I wonder if we could instead check out the complete mbedtls tree, here, so it is re-usable for TF-M. What would be the implications in building with Zephyr?

**Comment by MaureenHelm** [comment]
> > @d3zd3z Do you mind adding me as a reviewer to this, or is there a specific process for the crypto libs?
> 
> you need to be collaborator i the repository, I guess @galak can fix that.

Done

**Comment by ioannisg** [comment]
This was done. Closing :)

**Pull request closed without merging**
