### PR TITLE
mbedtls: bump mbedtls 3.0.0

### PR DESCRIPTION
**Pull request by ceolin**
Bump mbedtls version to 3.0.0 release.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by galak** [comment]
> Bump mbedtls version to 3.0.0 release.
> 
> Signed-off-by: Flavio Ceolin [flavio.ceolin@intel.com](mailto:flavio.ceolin@intel.com)

Would it make sense to create a new branch for 3.0 and have it pull in the commits from upstream mbedtls?

**Comment by ceolin** [comment]
> > Bump mbedtls version to 3.0.0 release.
> > Signed-off-by: Flavio Ceolin [flavio.ceolin@intel.com](mailto:flavio.ceolin@intel.com)
> 
> Would it make sense to create a new branch for 3.0 and have it pull in the commits from upstream mbedtls?

Probably. There was an extensive discussion about it last release and somehow we end up doing it. Right now I'm more focused in migrate Zephyr's code to this version, so I'm preparing a pr there and I need to have a revision to put in the manifest to test.

But you are right, I believe we got the point that we can use vanilla mbedTLS. I didn't need to carry any patch. I'll use it for now to validate the changes on Zephyr and meanwhile review the best approach to this repo.

**Comment by galak** [comment]
I added the v3.0.0 tag from upstream mbedtls into this repo and created a zephyr branch based on that tag.  We can utilize that as a starting point once you are ready.  (will need to add a commit to add zephyr integration dir).

**Comment by d3zd3z** [comment]
Currently, we need the Zephyr integration directory, and a Cmake file specifically for Zephyr. Once this gets working with Zephyr and 3.0, I'll begin working with upstream mbed TLS so that we can directly use the Mbed TLS CmakeLists.txt file. Right now, it does a few things that would disrupt the Zephyr build.

**Comment by galak** [comment]
> Currently, we need the Zephyr integration directory, and a Cmake file specifically for Zephyr. Once this gets working with Zephyr and 3.0, I'll begin working with upstream mbed TLS so that we can directly use the Mbed TLS CmakeLists.txt file. Right now, it does a few things that would disrupt the Zephyr build.

Where does the Zephyr Cmake file live today?

**Comment by d3zd3z** [comment]
> Where does the Zephyr Cmake file live today?

At the top of the zephyrproject-rtos/mbedtls repo in CMakeLists.txt-zephyr.

It should be fine to add this file, along with the zephyr directory as changes on top of a direct sync of the upstream. It would require minor tweaking to not have mbedtls as a separate subdirectory.

**Pull request closed without merging**
