### PR TITLE
mbedtls 3.1

### PR DESCRIPTION
**Pull request by ceolin**
Bump mbedTLS to 3.1

### CODE REVIEW

**Comment by rlubos** [comment]
Any update on this PR? Are there currently any blockers for getting mbed TLS 3.1 integrated with Zephyr?

**Comment by d3zd3z** [comment]
> Are there currently any blockers for getting mbed TLS 3.1 integrated with Zephyr?

I think we need to wait until there is a version of ~~Mbed TLS~~ **TF-M** released that supports Mbed TLS 3.1.

**Comment by d3zd3z** [comment]
I mistyped TF-M in my comment. There probably isn't anything blocking this repo from bringing in Mbed TLS 3.1, since we always refer to them explicitly by version in Zephyr's west.yaml. But, we will have to wait to use Mbed TLS 3.1 until TF-M supports it.

**Comment by microbuilder** [comment]
Current TF-M main is based on MbedTLS 3.1, so perhaps we can do an interim TF-M upmerge to test against until TF-M 1.6.0 is tagged. There are some fixes post 1.5.0 I'd like to have anyway.

**Comment by d3zd3z** [comment]
We'd have to ask at, I'm not sure maybe the TSC, but it kind of makes sense for us to pull in an interim release of TF-M during an interim version of Zephyr, as long as we get everything settled before the next Zephyr release.

**Comment by theotherjimmy** [comment]
Looks to me like the patches in TFM (see this dir: https://github.com/theotherjimmy/trusted-firmware-m-1/tree/update-tfm-pre-1.6.0/lib/ext/mbedcrypto) were not applied. In particular, without https://github.com/theotherjimmy/trusted-firmware-m-1/blob/update-tfm-pre-1.6.0/lib/ext/mbedcrypto/0003-Disable-export-MbedTLSTargets.patch, I can't build with the head of TFM.

**Comment by theotherjimmy** [comment]
Alternatively, from this repo: https://github.com/zephyrproject-rtos/mbedtls/commit/0e6e282532f3836c4a1b19be8bc304facd017e1a

**Review by microbuilder — APPROVED** [review]
Approving based on TF-M 1.6.0 testing.

**Comment by microbuilder** [comment]
Any objections to this? I'd like to get it in for the feature freeze Friday if possible.

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
