### PR TITLE
mbedtls: Update to mbedTLS 2.16.6

### PR DESCRIPTION
**Pull request by ceolin**
Bump mbedTLS to 2.16.6

Origin: ARMmbed/mbedTLS
License: Apache-2.0
URL: https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.16.6
commit: 2a1d9332d55d1270084232e42df08fdb08129f1b

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
@carlescufi  I can't assign reviewers for this pr, don't know why though.
@nashif ^

**Comment by carlescufi** [comment]
> @carlescufi I can't assign reviewers for this pr, don't know why though.
> @nashif ^

It's because this is a separate repo with its own set of collaborators. 
@pfalcon you have a pending invitation to join this repo.

**Comment by pfalcon** [comment]
> @pfalcon you have a pending invitation to join this repo.

acked.

**Comment by ceolin** [comment]
> Please add a counterpart PR to the main zephyr tree that references `pull/11/head` in `west.yml`
Ok. I was wondering how to validate these changes in CI, that is the way :)

**Comment by ceolin** [comment]
> I've tested the update with OpenThread, it works fine but due to a new check in the `check_config.h` sanitizer, some configs have to be tweaked in order to build the OpenTherad stack w/o errors. Here are commits with the changes I had to apply in `mbedtls` and `zephyr` repos to make it work:
> [rlubos@00a8c7e](https://github.com/rlubos/mbedtls/commit/00a8c7eef376ab1b9c74d2f1580f3173f289412a)
> [rlubos/zephyr@a3803d0](https://github.com/rlubos/zephyr/commit/a3803d020fbe3e878614af79664eb87db423b269)

@rlubos your patches looks good to me, will cherry pick them in my prs, ok ?

**Comment by rlubos** [comment]
@ceolin Sure, that's why I posted them 😄

**Comment by ceolin** [comment]
> @ceolin Sure, that's why I posted them smile

cool ! Done

**Comment by carlescufi** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/25841 is green, merging

**Pull request merged**
