### PR TITLE
cmake: Misc. cleanup of build scripts

### PR DESCRIPTION
**Pull request by SebastianBoe**
Misc. cleanup of build scripts. Most importantly, mbedTLS is no longer
linked with zephyr_interface. It should not be as there is no reason
to do so. This aligns with
https://github.com/zephyrproject-rtos/zephyr/pull/19346

Also, glob the source files in 'library' instead of listing them to
make it clear that all files are used.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
@carlescufi : FYI

**Comment by carlescufi** [comment]
@SebastianBoe can you post a PR in the zephyr repo that points to this so we can run CI?

**Comment by SebastianBoe** [comment]
Done.

https://github.com/zephyrproject-rtos/zephyr/pull/19745

**Comment by SebastianBoe** [comment]
CI is OK, can we merge this @carlescufi  ?

**Pull request merged**
