### PR TITLE
Bump mbedTLS to  3.2.1

### PR DESCRIPTION
**Pull request by ceolin**
mbedtls 3.2.1

### CODE REVIEW

**Comment by ceolin** [comment]
DO NOT MERGE. We have to have a new branch for this version otherwise we will break who depends in the current revision. This is for test Zephyr.

**Comment by microbuilder** [comment]
This is actually much further ahead than 3.2.1 (a couple hundred commits ahead, it seems): https://github.com/Mbed-TLS/mbedtls/commits/v3.2.1 ... can you resync to be based on the 3.2.1 tag upstream? Thanks.

**Comment by ceolin** [comment]
> This is actually much further ahead than 3.2.1 (a couple hundred commits ahead, it seems): [Mbed-TLS/mbedtls@`v3.2.1` (commits)](https://github.com/Mbed-TLS/mbedtls/commits/v3.2.1) ... can you resync to be based on the 3.2.1 tag upstream? Thanks.

The HEAD on https://github.com/Mbed-TLS/mbedtls/commits/v3.2.1 is 869298bffeea13b205343361b7a7daf2b210e33d
This pr is synced, the commit bellow the merge commit is using the same hash.

**Comment by ceolin** [comment]
```
ceolin@gale:~/zephyrproject/modules/crypto/mbedtls$ git diff v3.2.1
diff --git a/include/mbedtls/check_config.h b/include/mbedtls/check_config.h
index 5fe984984..5b4b20df9 100644
--- a/include/mbedtls/check_config.h
+++ b/include/mbedtls/check_config.h
@@ -867,9 +867,9 @@
 #endif
 #undef MBEDTLS_THREADING_IMPL
 
-#if defined(MBEDTLS_USE_PSA_CRYPTO) && !defined(MBEDTLS_PSA_CRYPTO_C)
-#error "MBEDTLS_USE_PSA_CRYPTO defined, but not all prerequisites"
-#endif
+// #if defined(MBEDTLS_USE_PSA_CRYPTO) && !defined(MBEDTLS_PSA_CRYPTO_C)
+// #error "MBEDTLS_USE_PSA_CRYPTO defined, but not all prerequisites"
+// #endif
 
 #if defined(MBEDTLS_VERSION_FEATURES) && !defined(MBEDTLS_VERSION_C)
 #error "MBEDTLS_VERSION_FEATURES defined, but not all prerequisites"
diff --git a/library/platform.c b/library/platform.c
index 6151e6c49..074ecbb72 100644
--- a/library/platform.c
+++ b/library/platform.c
@@ -53,8 +53,8 @@ static void platform_free_uninit( void *ptr )
 #define MBEDTLS_PLATFORM_STD_FREE     platform_free_uninit
 #endif /* !MBEDTLS_PLATFORM_STD_FREE */
 
-static void * (*mbedtls_calloc_func)( size_t, size_t ) = MBEDTLS_PLATFORM_STD_CALLOC;
-static void (*mbedtls_free_func)( void * ) = MBEDTLS_PLATFORM_STD_FREE;
+void * (*mbedtls_calloc_func)( size_t, size_t ) = MBEDTLS_PLATFORM_STD_CALLOC;
+void (*mbedtls_free_func)( void * ) = MBEDTLS_PLATFORM_STD_FREE;
 
 void * mbedtls_calloc( size_t nmemb, size_t size )
 {
diff --git a/library/platform_util.c b/library/platform_util.c
index 916a7f444..8936a9d7d 100644
--- a/library/platform_util.c
+++ b/library/platform_util.c
@@ -62,7 +62,7 @@
  * mbedtls_platform_zeroize() to use a suitable implementation for their
  * platform and needs.
  */
-static void * (* const volatile memset_func)( void *, int, size_t ) = memset;
+void * (* const volatile memset_func)( void *, int, size_t ) = memset;
 
 void mbedtls_platform_zeroize( void *buf, size_t len )
 {
diff --git a/zephyr/module.yml b/zephyr/module.yml
new file mode 100644
index 000000000..ab1e2b0f6
--- /dev/null
+++ b/zephyr/module.yml
@@ -0,0 +1,3 @@
+build:
+  cmake-ext: True
+  kconfig-ext: True
```

**Comment by ceolin** [comment]
I think it should be correct now. @microbuilder

**Comment by joerchan** [comment]
@ceolin While the diff seems to be correct you appear to not be doing the merge from `zephyr/main` branch.
The history for this PR looks like this:
```
git lol pr/40 --first-parent
* 6312c1619 (pr/40) Merge tag 'mbedtls-3.2.1' into mbedtls-3.2.1
* 126609c9b Merge tag 'v3.1.0' into zephyr
* 3e3e58a92 mbedtls: remove static keyword from certain function pointers
* 711fd5ea1 Merge pull request #33 from urutva/disable_dependency_check
* bf66e1804 Merge pull request #31 from d3zd3z/tozephyr
```
In comparison this is my upmerge:
```
git lol mbedtls-3.2.1-update --first-parent
* 82b638f4d (HEAD -> mbedtls-3.2.1-update) Merge tag 'v3.2.1'
* f49a9c8ec Revert "BUILD: Update IAR support in CMakeLists.txt"
* bfbac402e Revert "Disable export MbedTLSTargets"
* ed59cbdf1 Revert "CC3XX: Hardcode entry points for the CC3XX driver"
* 7fed49c9b (zephyr/zephyr, manifest-rev) CC3XX: Hardcode entry points for the CC3XX driver
* 99bad4d3b Disable export MbedTLSTargets
* 6db721618 BUILD: Update IAR support in CMakeLists.txt
* 126609c9b Merge tag 'v3.1.0' into zephyr
* 3e3e58a92 mbedtls: remove static keyword from certain function pointers
* 711fd5ea1 Merge pull request #33 from urutva/disable_dependency_check
* bf66e1804 Merge pull request #31 from d3zd3z/tozephyr
```
I think my approach is the correct one.
I've pushed the branch here:
https://github.com/joerchan/mbedtls/tree/mbedtls-3.2.1-update

I'm still puzzled why github shows a merge conflict here, maybe updating to my branch fixes it?

**Comment by carlescufi** [comment]
@ceolin you should not be getting merge conflicts on an update PR, so something is wrong with the way you ran this. @joerchan can you post an alternative PR from your branch so that we see if that one shows merge conflicts?

**Comment by joerchan** [comment]
@ceolin @carlescufi Created PR here : https://github.com/zephyrproject-rtos/mbedtls/pull/41

**Review by joerchan — CHANGES_REQUESTED** [review]
TF-M is applying 9 patches on top of the MBedTLS 3.2.1 tag.

I've created a PR that applies these patches in addition.
The patches could not be applied to this PR without merge conflicts, in addition there is merge conflicts in this PR already.

I suggest closing this in favour of #41.

**Comment by microbuilder** [comment]
> TF-M is applying 9 patches on top of the MBedTLS 3.2.1 tag.
> 
> I've created a PR that applies these patches in addition. The patches could not be applied to this PR without merge conflicts, in addition there is merge conflicts in this PR already.

Tested #41 with TF-M 1.7.0 and works fine here.

**Comment by ceolin** [comment]
> @ceolin you should not be getting merge conflicts on an update PR, so something is wrong with the way you ran this. @joerchan can you post an alternative PR from your branch so that we see if that one shows merge conflicts?

@carlescufi  this was for testing purpose and it wouldn't be merged in the current branch. Was for validation only.

**Comment by ceolin** [comment]
closing in favor of #41

**Pull request closed without merging**
