### PR TITLE
update to 3.6.2

### PR DESCRIPTION
**Pull request by tomi-font**
Reverted the patches we have on top of 3.6.1, merged `v3.6.2`, and re-applied the patches.
https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2

### CODE REVIEW

**Review by kartben — CHANGES_REQUESTED** [review]
zephyr/west.yml needs updating

**Review by frkv — APPROVED** [review]
LGTM

**Comment by tomi-font** [comment]
> zephyr/west.yml needs updating

Oh absolutely, good catch. (`zephyr/module.yml`, right? :wink:)

**Review by valeriosetti — APPROVED** [review]
LGTM :)

**Review by kartben — APPROVED** [review]

**Review by Vge0rge — APPROVED** [review]

**Pull request merged**
