### PR TITLE
configs: config-tls-generic.h: Add CONFIG_MBEDTLS_ECDSA_DETERMINISTIC

### PR DESCRIPTION
**Pull request by pfalcon**
From mbedTLS's description:

Enable deterministic ECDSA (RFC 6979).
Standard ECDSA is "fragile" in the sense that lack of entropy when signing
may result in a compromise of the long-term signing key. This is avoided by
the deterministic variant.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
cc: @rlubos 

This should be coupled with https://github.com/zephyrproject-rtos/zephyr/pull/18733

**Comment by rlubos** [comment]
Still, I think we should consider moving this config file back into the Zephyr tree (https://github.com/zephyrproject-rtos/mbedtls/pull/1#issuecomment-503534910).
IMO it's cumbersome to provide changes to this config file, as it requires 2 PRs in two different repositories. Feedback appreciated.

**Comment by pfalcon** [comment]
> Still, I think we should consider moving this config file back into the Zephyr tree (#1 (comment)).
IMO it's cumbersome to provide changes

It's very cumbersome, so +10 for such an initiative, if the need for such a split is not a fundamental west deficiency. Generally, I'd say we should strive for being able to use upstream repo as modules, and keep our *additions* (like config) on our side.

**Comment by pfalcon** [comment]
Oh my, but that's not enough, we now need to update west manifest to get our with @rlubos' changes in...

> Still, I think we should consider moving this config file back into the Zephyr tree (#1 (comment)).

@rlubos, if you want to proceed with that, then thumbs up again ;-).

**Pull request merged**
