### PR TITLE
Mbedtls 3.3.0 update

### PR DESCRIPTION
**Pull request by joerchan**

### CODE REVIEW

**Comment by d3zd3z** [comment]
Hmm, github is pretty worthless in allowing this to be reviewed. I'll spend some time looking at the commits with git directly.

**Comment by joerchan** [comment]
@d3zd3z Yeah, it's not easy to review what is happening here.
What I have done is to revert all of our patches that we applied on top of  the merge-commit with the mbedtls 3.2.1 tag.
Then I merged with the mbedtls 3.3.0 tag.
Then I have applied the patch history that TF-M keeps in it's repository, the commit message points to the patch file.

**Comment by SebastianBoe** [comment]
Are all the reverted patches from TF-M patch files, or does Zephyr have it's own set of patches?

**Comment by joerchan** [comment]
At the moment they are all from TF-M.

**Review by SebastianBoe — APPROVED** [review]
I have reviewed the changes to TF-M patch files and can confirm they correspond to how we revert and re-apply the patches.

So what we are doing is just as dangerous as before AFAICT.

**Comment by microbuilder** [comment]
@ceolin Do you mind do a test of this and a review?

**Comment by d3zd3z** [comment]
Reviewed the patches and done some basic testing.

**Review by d3zd3z — APPROVED** [review]
Reviewed the patches, and done some basic testing.

**Review by microbuilder — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
LGTM

**Pull request merged**
