### PR TITLE
mbedTLS v3.5.0 upmerge for TF-M v2.0.0

### PR DESCRIPTION
**Pull request by mswarowsky**
## Description

Please write a few sentences describing the overall goals of the pull request's commits.

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Review by d3zd3z — APPROVED** [review]

**Comment by SebastianBoe** [comment]
Hi, it looks like a set of commits were reverted before mbedtls 3.5.0 was merged.

May I ask why these commits were reverted and how one came up with this specific set?

**Comment by carlescufi** [comment]
@SebastianBoe can you please take a look?

**Comment by SebastianBoe** [comment]
This commit:

"library: Move mbedtls_ecc helper functions to psa_util"

will cause conflicts.

Is there a plan to upstream it?

**Comment by mswarowsky** [comment]
> Hi, it looks like a set of commits were reverted before mbedtls 3.5.0 was merged.
> 
> May I ask why these commits were reverted and how one came up with this specific set?

I don't understand what you mean can you specify which commits?

**Comment by SebastianBoe** [comment]
image

**Review by SebastianBoe — APPROVED** [review]

**Comment by mswarowsky** [comment]
> image

Discussed offline

**Review by ceolin — APPROVED** [review]

**Pull request merged**
